#!/bin/bash 
# This is the description of the script 
# This is it 
# This is life 

echo "Good day"
echo "Hello engineer Oluwafisayomi Posi Folaranmi" 
echo "You are a certified chemical engineer, and software engineering" 
echo "Work, and enjoy more"
echo "God bless you!" 

# u
